---
settings:
  name: On-premises ONTAP clusters
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: ONTAP-Cluster-Dokumentation vor Ort
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschr채nkungen
      url: "/reference-limitations.html"
  - title: Los geht's
    entries:
    - title: ONTAP-Cluster-Management vor Ort
      url: "/concept-onprem-ontap.html"
    - title: ONTAP Cluster erkennen
      url: "/task-discovering-ontap.html"
  - title: Management von lokalen ONTAP-Clustern
    entries:
    - title: Direktes Management von Clustern
      url: "/task-manage-ontap-direct.html"
    - title: Verwalten von Clustern, die 체ber einen Connector erkannt wurden
      url: "/task-manage-ontap-connector.html"
    - title: Cluster-Informationen und Vertragsdetails
      url: "/task-view-cluster-info.html"
    - title: Optimierung von Clustern mit Digital Advisor
      url: "/concept-aiq-digital-advisor.html"
    - title: Entfernen einer lokalen ONTAP-Arbeitsumgebung
      url: "/task-remove-on-prem.html"
  - title: Wissen und Support
    entries:
    - title: F체r den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: ONTAP-Cluster-Management vor Ort
      url: concept-onprem-ontap.html
    - title: ONTAP Cluster erkennen
      url: task-discovering-ontap.html
  - title: Management von lokalen ONTAP-Clustern
    links:
    - title: Direktes Management von Clustern
      url: task-manage-ontap-direct.html
    - title: Verwalten von Clustern, die 체ber einen Connector erkannt wurden
      url: task-manage-ontap-connector.html
  - title: Blogs Community
    links:
    - title: NetApp Community
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: BlueXP-Blog
      url: https://cloud.netapp.com/blog
    - title: Cloud-Webinare
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Alle BlueXP-Dokumentationen
