---
sidebar: sidebar 
permalink: task-manage-ontap-direct.html 
keywords: direct discovery, direct, system manager, local, local discovery 
summary: Wenn Sie Ihren lokalen ONTAP-Cluster direkt ohne Connector entdeckt haben, können Sie mit System Manager in die Arbeitsumgebung eingeben, in der das Cluster verwaltet werden soll. 
---
= Managen Sie lokale ONTAP-Cluster, die direkt entdeckt wurden
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie Ihren lokalen ONTAP-Cluster direkt ohne Connector entdeckt haben, können Sie die Arbeitsumgebung öffnen, in der das Cluster gemanagt werden soll, mit System Manager.

.Einschränkungen
Einige System Manager-Funktionen werden von BlueXP nicht unterstützt.

link:reference-limitations.html["Überprüfen Sie die Liste der Einschränkungen"].

.Schritte
. Doppelklicken Sie auf der Seite „Arbeitsfläche“ auf den Namen einer ONTAP-Arbeitsumgebung vor Ort.
. Geben Sie bei der entsprechenden Eingabeaufforderung Ihre ONTAP-Anmeldedaten ein.
+
Sie müssen sich bei jedem Öffnen der Arbeitsumgebung mit Ihren ONTAP-Anmeldeinformationen anmelden.

. Verwenden Sie System Manager zum Verwalten von ONTAP.
+
Wenn Sie Hilfe bei der Verwendung von System Manager mit ONTAP benötigen, finden Sie unter https://docs.netapp.com/us-en/ontap/index.html["ONTAP-Dokumentation"^] Schritt-für-Schritt-Anleitungen. Hier sind einige Links, die helfen könnten:

+
** https://docs.netapp.com/us-en/ontap/volume-admin-overview-concept.html["Volume- und LUN-Management"^]
** https://docs.netapp.com/us-en/ontap/network-manage-overview-concept.html["Netzwerkmanagement"^]
** https://docs.netapp.com/us-en/ontap/concept_dp_overview.html["Datensicherung"^]



